using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cerberus.Logic
{
    /// <summary>
    /// Script Operation Codes
    /// </summary>
    public enum ScriptOpCode : byte
    {
        End                                = 0x0,
        Return                             = 0x1,
        GetUndefined                       = 0x2,
        GetZero                            = 0x3,
        GetByte                            = 0x4,
        GetNegByte                         = 0x5,
        GetUnsignedShort                   = 0x6,
        GetNegUnsignedShort                = 0x7,
        GetInteger                         = 0x8,
        GetFloat                           = 0x9,
        GetString                          = 0xA,
        GetIString                         = 0xB,
        GetVector                          = 0xC,
        GetLevelObject                     = 0xD,
        GetAnimObject                      = 0xE,
        GetSelf                            = 0xF,
        GetLevel                           = 0x10,
        GetGame                            = 0x11,
        GetAnim                            = 0x12,
        GetAnimation                       = 0x13,
        GetGameRef                         = 0x14,
        GetFunction                        = 0x15,
        CreateLocalVariable                = 0x16,
        SafeCreateLocalVariables           = 0x17,
        RemoveLocalVariables               = 0x18,
        EvalLocalVariableCached            = 0x19,
        EvalArray                          = 0x1A,
        EvalLocalArrayRefCached            = 0x1B,
        EvalArrayRef                       = 0x1C,
        ClearArray                         = 0x1D,
        GetEmptyArray                      = 0x1E,
        GetSelfObject                      = 0x1F,
        EvalFieldVariable                  = 0x20,
        EvalFieldVariableRef               = 0x21,
        ClearFieldVariable                 = 0x22,
        SafeSetVariableFieldCached         = 0x23,
        SetWaittillVariableFieldCached     = 0x24,
        ClearParams                        = 0x25,
        CheckClearParams                   = 0x26,
        EvalLocalVariableRefCached         = 0x27,
        SetVariableField                   = 0x28,
        CallBuiltin                        = 0x29,
        CallBuiltinMethod                  = 0x2A,
        Wait                               = 0x2B,
        WaitTillFrameEnd                   = 0x2C,
        PreScriptCall                      = 0x2D,
        ScriptFunctionCall                 = 0x2E,
        ScriptFunctionCallPointer          = 0x2F,
        ScriptMethodCall                   = 0x30,
        ScriptMethodCallPointer            = 0x31,
        ScriptThreadCall                   = 0x32,
        ScriptThreadCallPointer            = 0x33,
        ScriptMethodThreadCall             = 0x34,
        ScriptMethodThreadCallPointer      = 0x35,
        DecTop                             = 0x36,
        CastFieldObject                    = 0x37,
        CastBool                           = 0x38,
        BoolNot                            = 0x39,
        BoolComplement                     = 0x3A,
        JumpOnFalse                        = 0x3B,
        JumpOnTrue                         = 0x3C,
        JumpOnFalseExpr                    = 0x3D,
        JumpOnTrueExpr                     = 0x3E,
        Jump                               = 0x3F,
        JumpBack                           = 0x40,
        Inc                                = 0x41,
        Dec                                = 0x42,
        Bit_Or                             = 0x43,
        Bit_Xor                            = 0x44,
        Bit_And                            = 0x45,
        Equal                              = 0x46,
        NotEqual                           = 0x47,
        LessThan                           = 0x48,
        GreaterThan                        = 0x49,
        LessThanOrEqualTo                  = 0x4A,
        GreaterThanOrEqualTo               = 0x4B,
        ShiftLeft                          = 0x4C,
        ShiftRight                         = 0x4D,
        Plus                               = 0x4E,
        Minus                              = 0x4F,
        Multiply                           = 0x50,
        Divide                             = 0x51,
        Modulus                            = 0x52,
        SizeOf                             = 0x53,
        WaitTillMatch                      = 0x54,
        WaitTill                           = 0x55,
        Notify                             = 0x56,
        EndOn                              = 0x57,
        VoidCodePos                        = 0x58,
        Switch                             = 0x59,
        EndSwitch                          = 0x5A,
        Vector                             = 0x5B,
        GetHash                            = 0x5C,
        RealWait                           = 0x5D,
        VectorConstant                     = 0x5E,
        IsDefined                          = 0x5F,
        VectorScale                        = 0x60,
        AnglesToUp                         = 0x61,
        AnglesToRight                      = 0x62,
        AnglesToForward                    = 0x63,
        AngleClamp180                      = 0x64,
        VectorToAngles                     = 0x65,
        Abs                                = 0x66,
        GetTime                            = 0x67,
        GetDvar                            = 0x68,
        GetDvarInt                         = 0x69,
        GetDvarFloat                       = 0x6A,
        GetDvarVector                      = 0x6B,
        GetDvarColorRed                    = 0x6C,
        GetDvarColorGreen                  = 0x6D,
        GetDvarColorBlue                   = 0x6E,
        GetDvarColorAlpha                  = 0x6F,
        FirstArrayKey                      = 0x70,
        NextArrayKey                       = 0x71,
        ProfileStart                       = 0x72,
        ProfileStop                        = 0x73,
        SafeDecTop                         = 0x74,
        Nop                                = 0x75,
        Abort                              = 0x76,
        Obj                                = 0x77,
        ThreadObject                       = 0x78,
        EvalLocalVariable                  = 0x79,
        EvalLocalVariableRef               = 0x7A,
        DevblockBegin                      = 0x7B,
        DevblockEnd                        = 0x7C,
        Breakpoint                         = 0x7D,
        AutoBreakpoint                     = 0x7E,
        ErrorBreakpoint                    = 0x7F,
        WatchBreakpoint                    = 0x80,
        NotifyBreakpoint                   = 0x81,
        GetObjectType,
        WaitRealTime,
        GetWorldObject,
        GetClassesObject,
        ClassFunctionCall,
        Bit_Not,
        GetWorld,
        EvalLevelFieldVariable,
        EvalLevelFieldVariableRef,
        EvalSelfFieldVariable,
        EvalSelfFieldVariableRef,
        SuperEqual,
        SuperNotEqual,
        Count,

        Invalid                               = 0xFF,
    }
}
